### ISSUE TITLE
Persistence Interface and implementation

### ISSUE THREAD

**Issue by lenseB** [MikaMk4/Gruppe5#13]

**Comment by MikaMk4** [comment]
sry dass ich das jetzt umbenannt habe aber ich konzentrier mich bei diesem issue gerade sehr auf persistence und da der branch, auf dem ich arbeite, mit diesem issue verbunden ist, wollte ich halt dass es entsprechend benannt ist. bei der frage ob und wie ich den branch noch umbenennen sollte bin ich mir nicht sicher.
